### PR TITLE
Add more configurations of the Dockerfiles for various uses

### PR DESCRIPTION
**Pull request by imikejackson**
Adds a Hyperthought docker container, a DREAM3_SDK docker container for circleci use and a DREAM3D build docker container.

All are based off of Ubuntu 18.04 with a custom ppa for the Qt5.11 install.

### CODE REVIEW

**Comment by psavery** [comment]
Hi Mike,

Thanks for the PR! I'll assume it's in good condition and accept it... but can you remove this file first:

    dream3d_sdk/dream3d_sdk/.Dockerfile.swp

Thanks!
Patrick

**Comment by imikejackson** [comment]
Sure. I'll get that removed. 
My belief is that it works. I was able to build a Docker container that has a DREAM3D_SDK based off the latest DREAM3DSuperbuild, then reuse that container to build DREAM.3D. I based my work off of the other directories in the repo. I figured others might want one of the flavors of the Docker files that are in this repository.

**Comment by imikejackson** [comment]
I removed the file and forced pushed so the file never shows up. I'm new to docker so if you have have feedback on how I wrote the Dockerfile I am happy to adjust the files.

**Comment by psavery** [comment]
Thanks @imikejackson!

**Pull request merged**
